# Dependabot configuration file
# See docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Enable version updates for npm/yarn
  - package-ecosystem: "npm" # Works for both npm and yarn
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" # Check for updates once a week
    versioning-strategy: "auto"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
